%{
  configs: [
    %{
      name: "default",
      strict: false,
      files: %{
        included: [
          "lib/",
          "src/",
          "test/",
          "web/",
          "apps/*/lib/",
          "apps/*/src/",
          "apps/*/test/",
          "apps/*/web/"
        ],
        excluded: [~r/\/_build\//, ~r/\/deps\//, ~r/\/node_modules\//]
      },
      requires: ["lib/nb_inertia/credo/check/**/*.ex"],
      color: true,
      plugins: [],
      parse_timeout: 5000,
      checks: %{
        disabled: [
          {Credo.Check.Readability.Specs, []},
          {Credo.Check.Refactor.ABCSize, []},
          {Credo.Check.Refactor.ModuleDependencies, []},
          {Credo.Check.Warning.LazyLogging, []},
          {Credo.Check.Warning.MixEnv, []},
          {Credo.Check.Warning.UnsafeToAtom, []}
        ],
        enabled: [
          {Credo.Check.Consistency.ExceptionNames, []},
          {Credo.Check.Consistency.LineEndings, []},
          {Credo.Check.Consistency.ParameterPatternMatching, []},
          {Credo.Check.Consistency.SpaceAroundOperators, []},
          {Credo.Check.Consistency.SpaceInParentheses, []},
          {Credo.Check.Consistency.TabsOrSpaces, []},
          {Credo.Check.Design.AliasUsage,
           [
             priority: :low,
             if_nested_deeper_than: 2,
             if_called_more_often_than: 0,
             excluded_namespaces: ["NbInertia", "Phoenix", "Plug"]
           ]},
          {Credo.Check.Design.TagTODO, [exit_status: 2]},
          {Credo.Check.Design.TagFIXME, []},
          {Credo.Check.Readability.AliasOrder, []},
          {Credo.Check.Readability.FunctionNames, []},
          {Credo.Check.Readability.LargeNumbers, []},
          {Credo.Check.Readability.MaxLineLength, [priority: :low, max_length: 120]},
          {Credo.Check.Readability.ModuleAttributeNames, []},
          {Credo.Check.Readability.ModuleDoc, [files: %{excluded: ["test/"]}]},
          {Credo.Check.Readability.ModuleNames, []},
          {Credo.Check.Readability.ParenthesesOnZeroArityDefs, []},
          {Credo.Check.Readability.ParenthesesInCondition, []},
          {Credo.Check.Readability.PipeIntoAnonymousFunctions, []},
          {Credo.Check.Readability.PredicateFunctionNames, []},
          {Credo.Check.Readability.PreferImplicitTry, []},
          {Credo.Check.Readability.RedundantBlankLines, []},
          {Credo.Check.Readability.Semicolons, []},
          {Credo.Check.Readability.SpaceAfterCommas, []},
          {Credo.Check.Readability.StringSigils, []},
          {Credo.Check.Readability.TrailingBlankLine, []},
          {Credo.Check.Readability.TrailingWhiteSpace, []},
          {Credo.Check.Readability.UnnecessaryAliasExpansion, []},
          {Credo.Check.Readability.VariableNames, []},
          {Credo.Check.Refactor.Apply, []},
          {Credo.Check.Refactor.CondStatements, []},
          {Credo.Check.Refactor.CyclomaticComplexity, []},
          {Credo.Check.Refactor.FunctionArity, [max_arity: 8]},
          {Credo.Check.Refactor.LongQuoteBlocks, []},
          {Credo.Check.Refactor.MapJoin, []},
          {Credo.Check.Refactor.MatchInCondition, []},
          {Credo.Check.Refactor.NegatedConditionsInUnless, []},
          {Credo.Check.Refactor.NegatedConditionsWithElse, []},
          {Credo.Check.Refactor.Nesting, []},
          {Credo.Check.Refactor.UnlessWithElse, []},
          {Credo.Check.Refactor.WithClauses, []},
          {Credo.Check.Refactor.FilterFilter, []},
          {Credo.Check.Refactor.RejectReject, []},
          {Credo.Check.Refactor.RedundantWithClauseResult, []},
          {Credo.Check.Warning.ApplicationConfigInModuleAttribute, []},
          {Credo.Check.Warning.BoolOperationOnSameValues, []},
          {Credo.Check.Warning.ExpensiveEmptyEnumCheck, []},
          {Credo.Check.Warning.IExPry, []},
          {Credo.Check.Warning.IoInspect, []},
          {Credo.Check.Warning.OperationOnSameValues, []},
          {Credo.Check.Warning.OperationWithConstantResult, []},
          {Credo.Check.Warning.RaiseInsideRescue, []},
          {Credo.Check.Warning.SpecWithStruct, []},
          {Credo.Check.Warning.WrongTestFileExtension, []},
          {Credo.Check.Warning.UnusedEnumOperation, []},
          {Credo.Check.Warning.UnusedFileOperation, []},
          {Credo.Check.Warning.UnusedKeywordOperation, []},
          {Credo.Check.Warning.UnusedListOperation, []},
          {Credo.Check.Warning.UnusedPathOperation, []},
          {Credo.Check.Warning.UnusedRegexOperation, []},
          {Credo.Check.Warning.UnusedStringOperation, []},
          {Credo.Check.Warning.UnusedTupleOperation, []},
          {Credo.Check.Warning.UnsafeExec, []},
          {NbInertia.Credo.Check.Design.DeclareInertiaPage, []},
          {NbInertia.Credo.Check.Design.FormInputsOptionalFieldConsistency, []},
          {NbInertia.Credo.Check.Readability.InertiaPageComponentNameCase, []},
          {NbInertia.Credo.Check.Readability.PropFromAssigns, []},
          {NbInertia.Credo.Check.Warning.ActionWithoutMount, []},
          {NbInertia.Credo.Check.Warning.AvoidRawInertiaRender, []},
          {NbInertia.Credo.Check.Warning.DirectRepoInController, []},
          {NbInertia.Credo.Check.Warning.InconsistentOptionalProps, []},
          {NbInertia.Credo.Check.Warning.MissingInertiaPageProps, []},
          {NbInertia.Credo.Check.Warning.MissingInertiaSharedProps, []},
          {NbInertia.Credo.Check.Warning.MissingMount, []},
          {NbInertia.Credo.Check.Warning.MissingSerializerInertiaProps, []},
          {NbInertia.Credo.Check.Warning.MixedInertiaControllerType, []},
          {NbInertia.Credo.Check.Warning.MixedPageAndController, []},
          {NbInertia.Credo.Check.Warning.ModalRequiresBaseUrl, []},
          {NbInertia.Credo.Check.Warning.ModalWithoutBaseUrl, []},
          {NbInertia.Credo.Check.Warning.RenderWithoutProps, []},
          {NbInertia.Credo.Check.Warning.UndeclaredPropInMount, []},
          {NbInertia.Credo.Check.Warning.UntypedInertiaProps, []},
          {NbInertia.Credo.Check.Warning.UnusedPropInMount, []},
          {NbInertia.Credo.Check.Warning.UseNbInertiaController, []}
        ]
      }
    }
  ]
}