defmodule NbInertia.Extractor.Preamble do
  @moduledoc """
  Generates TypeScript type preambles from Page module prop declarations.

  The preamble includes auto-generated header comments, import statements
  for serializer types, and a `Props` interface derived from the module's
  prop declarations.

  ## Type Mapping

  | Prop Declaration | Generated Type | Generated Import |
  |---|---|---|
  | `prop :name, :string` | `name: string` | -- |
  | `prop :count, :integer` | `count: number` | -- |
  | `prop :count, :number` | `count: number` | -- |
  | `prop :count, :float` | `count: number` | -- |
  | `prop :active, :boolean` | `active: boolean` | -- |
  | `prop :tags, :list` | `tags: any[]` | -- |
  | `prop :meta, :map` | `meta: Record<string, any>` | -- |
  | `prop :users, list: :string` | `users: string[]` | -- |
  | `prop :users, list: UserSerializer` | `users: User[]` | `import type { User } from '@/types'` |
  | `prop :user, UserSerializer` | `user: User` | `import type { User } from '@/types'` |
  | `prop :status, enum: ["a","b"]` | `status: 'a' \\| 'b'` | -- |
  | `prop :x, :map, nullable: true` | `x: Record<string, any> \\| null` | -- |
  | `prop :x, :string, default: ""` | `x?: string` | -- (optional with ?) |
  """

  @primitive_types [:string, :integer, :float, :boolean, :map, :list, :number, :any]

  @doc """
  Generates a complete TypeScript preamble string from a list of prop configs.

  ## Options

    * `:module` - The source Elixir module (for the header comment)
    * `:source_path` - The source file path (for the header comment)
    * `:types_import_path` - The import path for types (default: `"@/types"`)

  ## Returns

  A string containing:
  1. Auto-generated header comment
  2. Import statements for serializer types (if any)
  3. Props interface declaration
  """
  @spec generate(list(map()), keyword()) :: String.t()
  def generate(props, opts \\ []) do
    module = Keyword.get(opts, :module)
    source_path = Keyword.get(opts, :source_path)
    types_import_path = Keyword.get(opts, :types_import_path, "@/types")

    header = build_header(module, source_path)
    imports = build_imports(props, types_import_path)
    interface = build_interface(props)

    parts =
      [header, imports, interface]
      |> Enum.reject(&(&1 == ""))

    Enum.join(parts, "\n\n") <> "\n"
  end

  @doc """
  Converts a single prop config to its TypeScript type string.

  Returns the TypeScript type representation (e.g., `"string"`, `"User[]"`, `"'a' | 'b'"`).
  """
  @spec prop_to_ts_type(map()) :: String.t()
  def prop_to_ts_type(prop) do
    base_type = resolve_base_type(prop)
    nullable? = Keyword.get(prop[:opts] || [], :nullable, false)

    if nullable? do
      "#{base_type} | null"
    else
      base_type
    end
  end

  @doc """
  Extracts required type imports from a list of prop configs.

  Returns a list of `{type_name, module}` tuples for serializer types
  that need to be imported.
  """
  @spec extract_imports(list(map())) :: list({String.t(), module()})
  def extract_imports(props) do
    props
    |> Enum.flat_map(&extract_prop_imports/1)
    |> Enum.uniq_by(fn {name, _mod} -> name end)
    |> Enum.sort_by(fn {name, _mod} -> name end)
  end

  # ── Private Functions ──────────────────────────────────

  defp build_header(nil, _source_path),
    do: "// AUTO-GENERATED by NbInertia — do not edit directly"

  defp build_header(module, nil) do
    "// AUTO-GENERATED from #{inspect(module)} — do not edit directly"
  end

  defp build_header(module, source_path) do
    "// AUTO-GENERATED from #{inspect(module)} — do not edit directly\n// Source: #{source_path}"
  end

  defp build_imports(props, types_import_path) do
    imports = extract_imports(props)

    case imports do
      [] ->
        ""

      imports ->
        type_names = Enum.map_join(imports, ", ", fn {name, _mod} -> name end)
        "import type { #{type_names} } from '#{types_import_path}'"
    end
  end

  defp build_interface(props) do
    fields =
      props
      |> Enum.map(&format_interface_field/1)
      |> Enum.join("\n")

    "interface Props {\n#{fields}\n}"
  end

  defp format_interface_field(prop) do
    name = to_string(prop[:name] || prop.name)
    ts_type = prop_to_ts_type(prop)
    has_default? = Keyword.has_key?(prop[:opts] || [], :default)

    if has_default? do
      "  #{name}?: #{ts_type}"
    else
      "  #{name}: #{ts_type}"
    end
  end

  # ── Type Resolution ──────────────────────────────────

  defp resolve_base_type(%{type: :string}), do: "string"
  defp resolve_base_type(%{type: :integer}), do: "number"
  defp resolve_base_type(%{type: :float}), do: "number"
  defp resolve_base_type(%{type: :number}), do: "number"
  defp resolve_base_type(%{type: :boolean}), do: "boolean"
  defp resolve_base_type(%{type: :list}), do: "any[]"
  defp resolve_base_type(%{type: :map}), do: "Record<string, any>"
  defp resolve_base_type(%{type: :any}), do: "any"

  # Serializer type (single)
  defp resolve_base_type(%{serializer: serializer}) when is_atom(serializer) do
    serializer_type_name(serializer)
  end

  # No type or serializer — check opts for list:/enum:
  defp resolve_base_type(%{opts: opts} = prop) when is_list(opts) do
    cond do
      Keyword.has_key?(opts, :list) ->
        resolve_list_type(Keyword.get(opts, :list))

      Keyword.has_key?(opts, :enum) ->
        resolve_enum_type(Keyword.get(opts, :enum))

      true ->
        # Fallback: check if there's a type key we missed
        Map.get(prop, :type, :any) |> resolve_simple_type()
    end
  end

  defp resolve_base_type(_), do: "any"

  defp resolve_simple_type(:string), do: "string"
  defp resolve_simple_type(:integer), do: "number"
  defp resolve_simple_type(:float), do: "number"
  defp resolve_simple_type(:number), do: "number"
  defp resolve_simple_type(:boolean), do: "boolean"
  defp resolve_simple_type(:list), do: "any[]"
  defp resolve_simple_type(:map), do: "Record<string, any>"
  defp resolve_simple_type(:any), do: "any"
  defp resolve_simple_type(_), do: "any"

  # ── List Type Resolution ──────────────────────────────

  defp resolve_list_type(inner) when inner in @primitive_types do
    "#{resolve_simple_type(inner)}[]"
  end

  defp resolve_list_type(inner) when is_atom(inner) do
    # Serializer module
    "#{serializer_type_name(inner)}[]"
  end

  defp resolve_list_type(inner) when is_list(inner) do
    # Nested opts like [enum: ["admin", "user"]]
    cond do
      Keyword.has_key?(inner, :enum) ->
        "(#{resolve_enum_type(Keyword.get(inner, :enum))})[]"

      true ->
        "any[]"
    end
  end

  defp resolve_list_type(_), do: "any[]"

  # ── Enum Type Resolution ──────────────────────────────

  defp resolve_enum_type(values) when is_list(values) do
    values
    |> Enum.map_join(" | ", fn v -> "'#{v}'" end)
  end

  defp resolve_enum_type(_), do: "any"

  # ── Serializer Type Name ──────────────────────────────

  @doc """
  Derives a TypeScript type name from a serializer module name.

  Strips the "Serializer" suffix and takes the last module segment.

  ## Examples

      iex> NbInertia.Extractor.Preamble.serializer_type_name(UserSerializer)
      "User"

      iex> NbInertia.Extractor.Preamble.serializer_type_name(MyApp.PostSerializer)
      "Post"

      iex> NbInertia.Extractor.Preamble.serializer_type_name(MyApp.API.CommentSerializer)
      "Comment"

      iex> NbInertia.Extractor.Preamble.serializer_type_name(MyApp.Item)
      "Item"
  """
  @spec serializer_type_name(module()) :: String.t()
  def serializer_type_name(module) when is_atom(module) do
    module
    |> Module.split()
    |> List.last()
    |> String.replace_suffix("Serializer", "")
    |> case do
      "" -> Module.split(module) |> List.last()
      name -> name
    end
  end

  # ── Import Extraction ──────────────────────────────────

  defp extract_prop_imports(%{serializer: serializer}) when is_atom(serializer) do
    [{serializer_type_name(serializer), serializer}]
  end

  defp extract_prop_imports(%{opts: opts}) when is_list(opts) do
    case Keyword.get(opts, :list) do
      nil ->
        []

      inner when is_atom(inner) ->
        if inner in @primitive_types do
          []
        else
          [{serializer_type_name(inner), inner}]
        end

      _other ->
        []
    end
  end

  defp extract_prop_imports(_), do: []
end
