defmodule NbInertia.HTML do
  @moduledoc """
  HTML components for rendering Inertia.js pages.

  Provides components for both client-side and server-side rendered Inertia pages,
  as well as helpers for managing the page title and head tags.

  ## Components

  - `inertia_page/1` - Renders the root `<div>` for client-side rendering
  - `inertia_ssr/1` - Renders pre-rendered HTML with hydration data for SSR
  - `inertia_title/1` - Renders a `<title>` tag managed by Inertia's client-side router
  - `inertia_head/1` - Injects SSR-generated head tags (meta, link, etc.)
  """

  use Phoenix.Component

  @doc """
  Renders the Inertia page container for client-side rendering.

  Outputs a `<div id="app">` with the page data encoded as a `data-page` JSON attribute,
  which the Inertia.js client reads to mount the initial page component.
  """
  @doc type: :component
  attr(:page, :map,
    required: true,
    doc: "The Inertia page object (component, props, url, version)."
  )

  def inertia_page(assigns) do
    ~H"""
    <div id="app" data-page={json_library().encode!(@page)}></div>
    """
  end

  @doc """
  Renders the Inertia page container for server-side rendering.

  Outputs a `<div id="app">` containing both the pre-rendered HTML body and the
  page data as a `data-page` attribute. This allows the client to hydrate the
  server-rendered markup while having access to the full page data for subsequent
  navigation.
  """
  @doc type: :component
  attr(:page, :map, required: true, doc: "The Inertia page object.")
  attr(:body, :string, required: true, doc: "The pre-rendered HTML body from SSR.")

  def inertia_ssr(assigns) do
    ~H"""
    <div id="app" data-page={json_library().encode!(@page)}>
      {Phoenix.HTML.raw(@body)}
    </div>
    """
  end

  @doc """
  Renders a `<title>` tag with the `inertia` attribute.

  The `inertia` attribute tells the Inertia.js client to manage this title tag,
  updating it on client-side navigations via the `<Head>` component.

  This component handles the initial server-rendered title. For client-side title
  updates during SPA navigation, use the Inertia `<Head>` component in your
  page components.

  ## Examples

      <.inertia_title>My App</.inertia_title>
      <.inertia_title prefix="My App - "><%= assigns[:page_title] %></.inertia_title>
  """
  @doc type: :component
  attr(:prefix, :string, default: nil, doc: "Text prepended before the inner content.")
  attr(:suffix, :string, default: nil, doc: "Text appended after the inner content.")
  slot(:inner_block, required: true, doc: "The title text.")

  def inertia_title(assigns) do
    ~H"""
    <title data-prefix={@prefix} data-suffix={@suffix} inertia>
      {@prefix}{render_slot(@inner_block)}{@suffix}
    </title>
    """
  end

  @doc """
  Renders head tags generated by SSR.

  When server-side rendering is enabled, the SSR process may produce additional
  `<head>` tags (meta, link, script, etc.). This component injects them into the
  page's `<head>` section.
  """
  @doc type: :component
  attr(:content, :list, required: true, doc: "List of HTML tag strings to inject into `<head>`.")

  def inertia_head(assigns) do
    ~H"""
    {Phoenix.HTML.raw(Enum.join(@content, "\n"))}
    """
  end

  defp json_library do
    Phoenix.json_library()
  end
end
