/**
 * Runtime support for page contracts generated by nb_ts.
 *
 * This module deliberately has no React or Vue dependency.  A page schema is
 * looked up by Inertia component name and is evaluated before Inertia's page
 * resolver is allowed to commit a page to history or swap the component.
 *
 * The public registry contract is intentionally small:
 *
 *     const registry: PageSchemaRegistry = {
 *       get(component) {
 *         return pages[component]
 *       },
 *     }
 *
 * A schema may expose `safeParse`, `parse`, `decode`, `validate`, or
 * `transform`.  Generated schemas should prefer `safeParse` (with a
 * `{ success, data, error }` result) or a `parse` function.  `fields` is
 * supported for generated page schemas that want per-prop structural
 * sharing; fields not present in a partial/deferred response are untouched.
 */

export type SchemaRuntimePhase =
  | 'initial'
  | 'navigation'
  | 'partial'
  | 'deferred'
  | 'instant'
  | 'history'
  | 'modal'
  | 'prefetch'
  | 'ssr';

export type SchemaRuntimeMode = 'throw' | 'report' | 'off';

export type SchemaParser<T = unknown> = (value: unknown) => T | SchemaResult<T>;
export type SchemaValidator = (value: unknown) => unknown;

export interface SchemaSuccess<T = unknown> {
  success: true;
  data?: T;
  value?: T;
}

export interface SchemaFailureResult {
  success: false;
  error?: unknown;
  issues?: unknown;
}

export type SchemaResult<T = unknown> = SchemaSuccess<T> | SchemaFailureResult;

/** A parser/validator for one wire value. */
export interface PagePropSchema<T = unknown> {
  /** Wrapped generated schema (for example `{ schema: z.object(...), transforms: true }`). */
  schema?: unknown;
  safeParse?: (value: unknown) => SchemaResult<T>;
  parse?: SchemaParser<T>;
  decode?: SchemaParser<T>;
  validate?: SchemaValidator;
  transform?: (value: unknown) => T;
  /** Optional marker for generated schemas that perform a decode/transform. */
  transforms?: boolean;
  /** Explicit transform marker used by generated codec/Zod adapters. */
  decodeEnabled?: boolean;
  /** Alias accepted for generators that expose transform metadata. */
  isTransform?: boolean;
  /** Optional JSON-schema-like metadata accepted by generated registries. */
  type?: string | string[];
  enum?: readonly unknown[];
  required?: boolean | readonly string[];
  properties?: Record<string, PagePropSchema>;
  items?: PagePropSchema;
}

/**
 * A schema value accepted by the runtime's hand-written registry helpers.
 * Generated registries use `PageSchema`; the parser-function variant keeps
 * small test/ad-hoc registries ergonomic without changing that contract.
 */
export type PageSchemaValue = PageSchema | PagePropSchema | SchemaParser;

/** A page-level schema, optionally with per-prop schemas. */
export interface PageSchema<
  T extends Record<string, unknown> = Record<string, unknown>,
> extends PagePropSchema<T> {
  /** Complete page parser used for initial/navigation/history/SSR snapshots. */
  fullSchema?: unknown;
  /** Alias for a complete wire-input parser. */
  wireSchema?: unknown;
  fields?: Record<string, PagePropSchema>;
  /** `props` and `shape` are accepted as aliases used by generators. */
  props?: Record<string, PagePropSchema>;
  shape?: Record<string, PagePropSchema>;
  propertySchemas?: Record<string, PagePropSchema>;
  /** `required` also accepts the page-field list emitted by nb_ts. */
  /** Field-local transform markers emitted by nb_ts. */
  transformFields?: Readonly<Record<string, true>>;
  /** JSON-schema-like aliases used by some generated registries. */
}

/**
 * The stable registry interface generated page registries should implement.
 * The runtime accepts a few structural fallbacks for hand-written registries
 * (object maps and lookup functions), but `get` is the supported contract.
 */
export interface PageSchemaRegistry {
  get(component: string): PageSchemaValue | undefined;
  /**
   * Indicates that this registry can contain transformed schemas. It is only
   * a capability marker; it must not turn ordinary validation failures into
   * decode failures. Generated entries should mark the individual schema (or
   * field) that actually decodes wire data.
   */
  transforms?: boolean;
}

export type PageSchemaRegistryLike =
  | PageSchemaRegistry
  | Record<string, PageSchemaValue>
  | ((component: string) => PageSchemaValue | undefined)
  | {
      lookup?: (component: string) => PageSchemaValue | undefined;
      getPageSchema?: (component: string) => PageSchemaValue | undefined;
      pages?: Record<string, PageSchemaValue>;
    };

export interface PageLike {
  component: string;
  props: Record<string, unknown>;
  [key: string]: unknown;
}

export interface SchemaFailure {
  /** The category is intentionally stable for reporting and telemetry. */
  kind: 'validation' | 'decode';
  /** Alias that makes the distinction easy to consume in error handlers. */
  stage: 'validation' | 'decode';
  component: string;
  prop?: string;
  path?: string;
  phase: SchemaRuntimePhase;
  value?: unknown;
  error?: unknown;
  issues?: unknown;
}

export class PageSchemaRuntimeError extends Error {
  readonly failure: SchemaFailure;

  constructor(failure: SchemaFailure) {
    const location = failure.prop ? `${failure.component}.${failure.prop}` : failure.component;
    const detail =
      failure.kind === 'validation' ? 'failed validation' : 'failed decoding/transform';
    super(`Inertia page ${location} ${detail}`);
    this.name = 'PageSchemaRuntimeError';
    this.failure = failure;
  }
}

export type SchemaFailureReporter = (failure: SchemaFailure) => void;

export interface PageSchemaRuntimeOptions {
  registry?: PageSchemaRegistryLike | null;
  enabled?: boolean;
  mode?: SchemaRuntimeMode;
  /** Alias for `mode`, useful when mirroring server policy terminology. */
  policy?: SchemaRuntimeMode;
  /** Called for report and throw modes before the error is handled/thrown. */
  onFailure?: SchemaFailureReporter;
  /** Alias retained for callers that use reporter terminology. */
  reporter?: SchemaFailureReporter;
  /** Optional Vite/LiveReload overlay hook in development. */
  overlay?: SchemaFailureReporter;
}

export interface InertiaRouterLike {
  // `init` is intentionally broad here.  React and Vue use the same Inertia
  // router but expose framework-specific component/swap callback types.
  init?: (params: any) => unknown;
  on?: (event: any, callback: any) => (() => void) | void;
}

export interface RouterInitParamsLike {
  initialPage: PageLike;
  resolveComponent: (name: string, page?: PageLike) => unknown;
  [key: string]: unknown;
}

export interface SchemaRuntime {
  readonly enabled: boolean;
  readonly mode: SchemaRuntimeMode;
  readonly registry?: PageSchemaRegistryLike | null;
  processPage(page: unknown, phase?: SchemaRuntimePhase): unknown;
  processProps(
    component: string,
    props: unknown,
    phase?: SchemaRuntimePhase,
    schema?: PageSchema | PagePropSchema,
  ): unknown;
  phaseForPage(page?: unknown): SchemaRuntimePhase;
  dispose(): void;
}

export interface InstalledSchemaRuntime extends SchemaRuntime {
  readonly router?: InertiaRouterLike;
}

export interface PageSchemaAppOptions {
  /** Runtime configuration passed through the framework createInertiaApp wrapper. */
  schemaRuntime?: PageSchemaRuntimeOptions | false;
  /** A convenient alias for callers that already use this name. */
  pageSchemaRuntime?: PageSchemaRuntimeOptions | false;
  /** A convenient shorthand for `schemaRuntime.registry`. */
  pageSchemas?: PageSchemaRegistryLike | null;
}

const RUNTIME_INSTALLATION = Symbol.for('nb_inertia.page_schema_runtime');
const RUNTIME_CONFIG_GLOBAL = '__NB_INERTIA_PAGE_SCHEMA_RUNTIME__';

function readGlobalRuntimeConfig(): PageSchemaRuntimeOptions | false | undefined {
  return (globalThis as Record<string, unknown>)[RUNTIME_CONFIG_GLOBAL] as
    | PageSchemaRuntimeOptions
    | false
    | undefined;
}

type CachedResult =
  | { ok: true; value: unknown }
  | {
      ok: false;
      failure: Omit<SchemaFailure, 'phase' | 'component' | 'prop' | 'path' | 'value'> & {
        error?: unknown;
        issues?: unknown;
      };
    };

type RuntimeState = {
  phase: SchemaRuntimePhase;
  disposed: boolean;
  pageCache: WeakMap<object, unknown>;
  registryCache: Map<string, PageSchemaValue | null>;
  objectCache: WeakMap<object, WeakMap<object, CachedResult>>;
  primitiveCache: Map<unknown, WeakMap<object, CachedResult>>;
  unsubs: Array<() => void>;
};

let configuredRuntime: PageSchemaRuntimeOptions | false | undefined = readGlobalRuntimeConfig();

const NORMALIZED_SCHEMA_CACHE = new WeakMap<object, PageSchema | PagePropSchema>();

/**
 * Configure the defaults used by the framework adapters when no per-app
 * `schemaRuntime` option is supplied.  This is useful for generated `lib`
 * entrypoints and remains opt-in: without a registry there is no work.
 */
export function configurePageSchemaRuntime(
  options: PageSchemaRuntimeOptions | false | undefined,
): PageSchemaRuntimeOptions | false | undefined {
  configuredRuntime = options;
  try {
    if (options === undefined) {
      delete (globalThis as Record<string, unknown>)[RUNTIME_CONFIG_GLOBAL];
    } else {
      (globalThis as Record<string, unknown>)[RUNTIME_CONFIG_GLOBAL] = options;
    }
  } catch {
    // A restricted host may not allow global properties. The module-local
    // value remains sufficient once this runtime module is loaded.
  }
  return configuredRuntime;
}

export function getPageSchemaRuntimeConfig(): PageSchemaRuntimeOptions | false | undefined {
  return readGlobalRuntimeConfig() ?? configuredRuntime;
}

export function clearPageSchemaRuntimeConfig(): void {
  configuredRuntime = undefined;
  try {
    delete (globalThis as Record<string, unknown>)[RUNTIME_CONFIG_GLOBAL];
  } catch {
    // Ignore non-configurable host globals.
  }
}

/** Build the supported `get(component)` registry shape from an object map. */
export function createPageSchemaRegistry(
  pages: Record<string, PageSchemaValue>,
): PageSchemaRegistry {
  return {
    get(component: string) {
      return pages[component];
    },
  };
}

export function isPageSchemaRuntimeError(error: unknown): error is PageSchemaRuntimeError {
  return error instanceof PageSchemaRuntimeError;
}

function isObject(value: unknown): value is object {
  return (typeof value === 'object' && value !== null) || typeof value === 'function';
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function hasOwn(value: object, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

function isProductionEnvironment(): boolean {
  const processLike = (globalThis as { process?: { env?: { NODE_ENV?: string } } }).process;
  return processLike?.env?.NODE_ENV === 'production';
}

function defaultMode(): SchemaRuntimeMode {
  return isProductionEnvironment() ? 'off' : 'throw';
}

function resolveOptions(
  options: PageSchemaRuntimeOptions | false | undefined,
  shorthandRegistry?: PageSchemaRegistryLike | null,
): PageSchemaRuntimeOptions {
  const configured = readGlobalRuntimeConfig() ?? configuredRuntime;

  if (options === false) {
    return { enabled: false, mode: 'off' };
  }

  const source = options || (configured === false ? undefined : configured) || {};
  const registry =
    options && options.registry !== undefined
      ? options.registry
      : (shorthandRegistry ?? source.registry);

  return {
    ...source,
    registry,
    mode: source.mode || source.policy || defaultMode(),
    enabled: source.enabled !== false,
  };
}

function lookupRegistry(
  registry: PageSchemaRegistryLike | null | undefined,
  component: string,
  cache: Map<string, PageSchemaValue | null>,
): PageSchemaValue | undefined {
  if (!registry) return undefined;
  if (cache.has(component)) return cache.get(component) || undefined;

  let result: PageSchemaValue | undefined;

  try {
    if (typeof registry === 'function') {
      result = registry(component);
    } else if (typeof (registry as PageSchemaRegistry).get === 'function') {
      result = (registry as PageSchemaRegistry).get(component);
    } else if (typeof (registry as { lookup?: unknown }).lookup === 'function') {
      result = (registry as { lookup: (name: string) => PageSchemaValue | undefined }).lookup(
        component,
      );
    } else if (typeof (registry as { getPageSchema?: unknown }).getPageSchema === 'function') {
      result = (
        registry as { getPageSchema: (name: string) => PageSchemaValue | undefined }
      ).getPageSchema(component);
    } else if (isRecord((registry as { pages?: unknown }).pages)) {
      result = (registry as { pages: Record<string, PageSchemaValue> }).pages[component];
    } else if (isRecord(registry)) {
      result = (registry as Record<string, PageSchemaValue>)[component];
    }
  } catch (error) {
    // Registry lookup errors should not be mistaken for a wire-data error.
    // Let the runtime report them as an unavailable schema by skipping this
    // component; generated registries should have a total, side-effect-free
    // `get` implementation.
    result = undefined;
    void error;
  }

  cache.set(component, result || null);
  return result;
}

function normalizeSchema(
  schema: PageSchemaValue | undefined,
): PageSchema | PagePropSchema | undefined {
  if (typeof schema === 'function') {
    return { parse: schema as SchemaParser };
  }
  if (!isObject(schema)) return undefined;

  const cached = NORMALIZED_SCHEMA_CACHE.get(schema);
  if (cached) return cached;

  const candidate = schema as PageSchema | PagePropSchema;
  const wrapped = candidate.schema;
  if (wrapped !== undefined && !hasSchemaOperation(candidate) && !schemaFields(candidate)) {
    const inner = normalizeSchema(wrapped as PageSchema | PagePropSchema);
    if (!inner) return undefined;

    // Preserve metadata while still executing the generated schema object.
    // The marker is important: a failed Zod transform is a decode failure and
    // must never expose the original wire value as a fallback.
    if (
      candidate.transforms === true ||
      candidate.decodeEnabled === true ||
      candidate.isTransform === true
    ) {
      const normalized = { ...inner, transforms: true };
      NORMALIZED_SCHEMA_CACHE.set(schema, normalized);
      return normalized;
    }
    NORMALIZED_SCHEMA_CACHE.set(schema, inner);
    return inner;
  }

  NORMALIZED_SCHEMA_CACHE.set(schema, candidate);
  return candidate;
}

function schemaFields(
  schema: PageSchema | PagePropSchema,
): Record<string, PagePropSchema> | undefined {
  const candidate = schema as PageSchema;

  for (const key of ['fields', 'props', 'shape', 'propertySchemas', 'properties']) {
    // Zod object schemas expose a prototype `shape` getter. Only accept the
    // explicit page-entry aliases emitted by nb_ts (or supplied as own
    // properties by a hand-written registry), otherwise a whole Zod schema
    // would be mistaken for a field map and lose whole-page issue context.
    if (!hasOwn(candidate, key)) continue;
    const value = (candidate as unknown as Record<string, unknown>)[key];
    if (isRecord(value)) {
      return value as Record<string, PagePropSchema>;
    }
  }

  return undefined;
}

function hasTransform(schema: PagePropSchema): boolean {
  const zodLike =
    isObject(schema) &&
    ('_def' in (schema as object) || 'def' in (schema as object)) &&
    (typeof schema.safeParse === 'function' || typeof schema.parse === 'function');

  return (
    schema.transforms === true ||
    schema.decodeEnabled === true ||
    schema.isTransform === true ||
    // Zod exposes `.transform()` as a builder on every schema. It is not a
    // transform marker, so only treat a generic callback as such for
    // non-Zod schema implementations. Zod codecs/pipes are identified from
    // their definition below (or by explicit generated markers).
    (typeof schema.transform === 'function' && !zodLike) ||
    zodSchemaHasTransform(schema) ||
    (typeof schema.decode === 'function' && !zodLike)
  );
}

/**
 * Zod 4 keeps codec/transform metadata in `_def`. Generated nb_ts schemas
 * additionally mark transformed fields explicitly, but this narrow structural
 * check keeps existing `pageSchemaRegistry { transforms: true }` output safe:
 * plain Zod validation remains `validation`, while codecs are `decode`.
 */
function zodSchemaHasTransform(schema: unknown, seen = new Set<object>(), depth = 0): boolean {
  if (!isObject(schema) || depth > 12 || seen.has(schema)) return false;
  seen.add(schema);

  const candidate = schema as Record<string, unknown>;
  if (candidate.__nb_inertia_transform__ === true || candidate.__nb_transform__ === true)
    return true;

  const definition = candidate._def ?? candidate.def;
  if (!isObject(definition)) {
    // Zod object shapes are ordinary records. Walking their values is safe
    // here because this function is only reached from a schema definition or
    // a bounded child reference.
    return Object.values(candidate).some((value) => zodSchemaHasTransform(value, seen, depth + 1));
  }
  const type = (definition as Record<string, unknown>).type;
  if (type === 'transform' || type === 'codec' || type === 'preprocess') return true;
  if (
    type === 'pipe' &&
    isObject((definition as Record<string, unknown>).in) &&
    isObject((definition as Record<string, unknown>).out)
  ) {
    return (
      zodSchemaHasTransform((definition as Record<string, unknown>).in, seen, depth + 1) ||
      zodSchemaHasTransform((definition as Record<string, unknown>).out, seen, depth + 1) ||
      typeof (definition as Record<string, unknown>).transform === 'function' ||
      typeof (definition as Record<string, unknown>).reverseTransform === 'function' ||
      typeof (definition as Record<string, unknown>).decode === 'function' ||
      typeof (definition as Record<string, unknown>).encode === 'function'
    );
  }
  if ((definition as Record<string, unknown>).coerce === true) return true;

  for (const key of [
    'in',
    'out',
    'innerType',
    'schema',
    'element',
    'items',
    'left',
    'right',
    'valueType',
    'keyType',
    'options',
  ]) {
    const value = (definition as Record<string, unknown>)[key];
    if (Array.isArray(value)) {
      if (value.some((item) => zodSchemaHasTransform(item, seen, depth + 1))) return true;
    } else if (zodSchemaHasTransform(value, seen, depth + 1)) {
      return true;
    }
  }

  const shape = (definition as Record<string, unknown>).shape;
  if (typeof shape === 'function') {
    try {
      return zodSchemaHasTransform(shape(), seen, depth + 1);
    } catch {
      return false;
    }
  }
  return zodSchemaHasTransform(shape, seen, depth + 1);
}

function hasSchemaOperation(schema: PagePropSchema): boolean {
  return (
    typeof schema.safeParse === 'function' ||
    typeof schema.parse === 'function' ||
    typeof schema.decode === 'function' ||
    typeof schema.transform === 'function' ||
    typeof schema.validate === 'function' ||
    typeof schema.type === 'string' ||
    Array.isArray(schema.type) ||
    Array.isArray(schema.enum) ||
    isRecord(schema.properties) ||
    !!schema.items
  );
}

function normalizeValidation(
  value: unknown,
): { ok: true } | { ok: false; error?: unknown; issues?: unknown } {
  if (value === undefined || value === null || value === true) return { ok: true };
  if (value === false) return { ok: false };

  if (isRecord(value)) {
    if (value.success === false || value.valid === false || value.ok === false) {
      const error = value.error;
      return {
        ok: false,
        error,
        issues: value.issues || value.errors || (isRecord(error) ? error.issues : undefined),
      };
    }

    if (value.success === true || value.valid === true || value.ok === true) {
      return { ok: true };
    }

    if ('error' in value && value.error !== undefined && value.error !== null) {
      return {
        ok: false,
        error: value.error,
        issues:
          value.issues || value.errors || (isRecord(value.error) ? value.error.issues : undefined),
      };
    }

    if (Array.isArray(value.issues) && value.issues.length > 0) {
      return { ok: false, issues: value.issues };
    }

    if (Array.isArray(value.errors) && value.errors.length > 0) {
      return { ok: false, issues: value.errors };
    }
  }

  if (Array.isArray(value) && value.length > 0) {
    return { ok: false, issues: value };
  }

  return { ok: true };
}

function normalizeParserResult(
  value: unknown,
): { ok: true; value: unknown } | { ok: false; error?: unknown; issues?: unknown } {
  if (!isRecord(value)) return { ok: true, value };

  if (value.success === false || value.ok === false) {
    const error = value.error;
    return {
      ok: false,
      error,
      issues: value.issues || value.errors || (isRecord(error) ? error.issues : undefined),
    };
  }

  if (value.success === true) {
    return { ok: true, value: 'data' in value ? value.data : value.value };
  }

  if (value.ok === true) {
    return { ok: true, value: 'value' in value ? value.value : value.data };
  }

  // A parser returning an object with an error but no success marker is an
  // error result in the same spirit as common decoder libraries.
  if ('error' in value && value.error !== undefined && value.error !== null) {
    return {
      ok: false,
      error: value.error,
      issues:
        value.issues || value.errors || (isRecord(value.error) ? value.error.issues : undefined),
    };
  }

  return { ok: true, value };
}

function readCached(
  state: RuntimeState,
  input: unknown,
  schema: PagePropSchema,
): CachedResult | undefined {
  if (isObject(input)) {
    return state.objectCache.get(input)?.get(schema as object);
  }

  return state.primitiveCache.get(input)?.get(schema as object);
}

function writeCached(
  state: RuntimeState,
  input: unknown,
  schema: PagePropSchema,
  result: CachedResult,
): void {
  if (isObject(input)) {
    let cache = state.objectCache.get(input);
    if (!cache) {
      cache = new WeakMap<object, CachedResult>();
      state.objectCache.set(input, cache);
    }
    cache.set(schema as object, result);
    return;
  }

  let cache = state.primitiveCache.get(input);
  if (!cache) {
    cache = new WeakMap<object, CachedResult>();
    state.primitiveCache.set(input, cache);
  }
  cache.set(schema as object, result);
}

function jsonSchemaValidation(value: unknown, schema: PagePropSchema, path: string): unknown[] {
  const issues: unknown[] = [];

  if (Array.isArray(schema.enum) && !schema.enum.some((item) => Object.is(item, value))) {
    issues.push({ path, message: 'must be one of the declared enum values' });
    return issues;
  }

  if (schema.type) {
    const types = Array.isArray(schema.type) ? schema.type : [schema.type];
    const valid = types.some((type) => {
      switch (type) {
        case 'null':
          return value === null;
        case 'array':
          return Array.isArray(value);
        case 'object':
          return isRecord(value);
        case 'integer':
          return typeof value === 'number' && Number.isInteger(value);
        case 'number':
          return typeof value === 'number' && Number.isFinite(value);
        case 'boolean':
          return typeof value === 'boolean';
        case 'string':
          return typeof value === 'string';
        default:
          return true;
      }
    });

    if (!valid) {
      issues.push({ path, message: `expected ${types.join(' or ')}` });
      return issues;
    }
  }

  if (Array.isArray(value) && schema.items) {
    value.forEach((item, index) => {
      issues.push(
        ...jsonSchemaValidation(item, schema.items as PagePropSchema, `${path}[${index}]`),
      );
    });
  }

  if (isRecord(value) && schema.properties) {
    for (const [key, childSchema] of Object.entries(schema.properties)) {
      if (hasOwn(value, key)) {
        issues.push(...jsonSchemaValidation(value[key], childSchema, `${path}.${key}`));
      } else if (childSchema.required) {
        issues.push({ path: `${path}.${key}`, message: 'is required' });
      }
    }
  }

  return issues;
}

function parserFor(
  schema: PagePropSchema,
):
  | { kind: 'safeParse'; fn: (value: unknown) => unknown }
  | { kind: 'decode'; fn: (value: unknown) => unknown }
  | { kind: 'parse'; fn: (value: unknown) => unknown }
  | { kind: 'transform'; fn: (value: unknown) => unknown }
  | undefined {
  if (typeof schema.safeParse === 'function')
    return { kind: 'safeParse', fn: schema.safeParse.bind(schema) };
  if (typeof schema.decode === 'function') {
    // Zod 4 exposes `decode` on every schema, even validators that do not
    // transform. Use the structural marker to avoid relabeling ordinary Zod
    // validation as a decode failure.
    return { kind: hasTransform(schema) ? 'decode' : 'parse', fn: schema.decode.bind(schema) };
  }
  if (typeof schema.parse === 'function') return { kind: 'parse', fn: schema.parse.bind(schema) };
  if (typeof schema.transform === 'function')
    return { kind: 'transform', fn: schema.transform.bind(schema) };
  return undefined;
}

function executeSchema(state: RuntimeState, schema: PagePropSchema, input: unknown): CachedResult {
  const cached = readCached(state, input, schema);
  if (cached) return cached;

  const fail = (
    kind: 'validation' | 'decode',
    error?: unknown,
    issues?: unknown,
  ): CachedResult => ({
    ok: false,
    failure: { kind, stage: kind, error, issues },
  });

  if (typeof schema.validate === 'function' && !parserFor(schema)) {
    try {
      const validation = normalizeValidation(schema.validate(input));
      if (!validation.ok) {
        const result = fail('validation', validation.error, validation.issues);
        writeCached(state, input, schema, result);
        return result;
      }
    } catch (error) {
      const result = fail('validation', error);
      writeCached(state, input, schema, result);
      return result;
    }
  } else if (typeof schema.validate === 'function') {
    // A separate validation callback is useful for transforms: it prevents a
    // transform from ever seeing invalid wire data and preserves the failure
    // category for diagnostics.
    try {
      const validation = normalizeValidation(schema.validate(input));
      if (!validation.ok) {
        const result = fail('validation', validation.error, validation.issues);
        writeCached(state, input, schema, result);
        return result;
      }
    } catch (error) {
      const result = fail('validation', error);
      writeCached(state, input, schema, result);
      return result;
    }
  }

  if (!hasSchemaOperation(schema)) {
    const result: CachedResult = { ok: true, value: input };
    writeCached(state, input, schema, result);
    return result;
  }

  const jsonIssues = jsonSchemaValidation(input, schema, '$');
  if (jsonIssues.length > 0) {
    const result = fail('validation', undefined, jsonIssues);
    writeCached(state, input, schema, result);
    return result;
  }

  const parser = parserFor(schema);
  if (!parser) {
    const result: CachedResult = { ok: true, value: input };
    writeCached(state, input, schema, result);
    return result;
  }

  try {
    const parsed = normalizeParserResult(parser.fn(input));
    if (!parsed.ok) {
      // A safe decoder with transforms must never be treated as a validation
      // warning followed by the original wire value.  Its output is unsafe.
      const kind =
        hasTransform(schema) || parser.kind === 'decode' || parser.kind === 'transform'
          ? 'decode'
          : 'validation';
      const result = fail(kind, parsed.error, parsed.issues);
      writeCached(state, input, schema, result);
      return result;
    }

    const result: CachedResult = { ok: true, value: parsed.value };
    writeCached(state, input, schema, result);
    return result;
  } catch (error) {
    const kind =
      hasTransform(schema) || parser.kind === 'decode' || parser.kind === 'transform'
        ? 'decode'
        : 'validation';
    const result = fail(kind, error);
    writeCached(state, input, schema, result);
    return result;
  }
}

function sameOwnValues(left: Record<string, unknown>, right: Record<string, unknown>): boolean {
  const keys = new Set([...Object.keys(left), ...Object.keys(right)]);
  for (const key of keys) {
    if (!Object.is(left[key], right[key])) return false;
  }
  return true;
}

function topLevelIssuePaths(issues: unknown): Set<string> {
  const paths = new Set<string>();
  const unsafeKeys = new Set(['__proto__', 'prototype', 'constructor']);
  if (!Array.isArray(issues)) return paths;

  for (const issue of issues) {
    if (isRecord(issue)) {
      const path = issue.path;
      if (typeof path === 'string') {
        // Zod commonly reports `$.field` while JSON-schema adapters may
        // report `field[0].name`. Strip only the root marker and select the
        // first own-property segment; never treat `$` or a prototype key as a
        // prop name by accident.
        const normalized = path.replace(/^\$\.?/, '');
        const first = normalized.split(/[.[\]]/)[0];
        if (first && !unsafeKeys.has(first)) paths.add(first);
      }
      if (
        Array.isArray(path) &&
        typeof path[0] === 'string' &&
        path[0] &&
        !unsafeKeys.has(path[0])
      ) {
        paths.add(path[0]);
      }
    }
  }

  return paths;
}

function copyPageInto(target: PageLike, source: PageLike): void {
  if (target === source) return;
  Object.assign(target, source);
}

function isCompletePhase(phase: SchemaRuntimePhase): boolean {
  return phase !== 'partial' && phase !== 'deferred';
}

function isRequiredSchemaField(schema: PagePropSchema, field: string): boolean {
  if (schema.required === true) return true;
  return Array.isArray(schema.required) && schema.required.includes(field);
}

function createRuntime(
  options: PageSchemaRuntimeOptions,
  router?: InertiaRouterLike,
): InstalledSchemaRuntime {
  const enabled = options.enabled !== false && options.mode !== 'off' && !!options.registry;
  const mode = options.mode || defaultMode();
  const state: RuntimeState = {
    phase: 'navigation',
    disposed: false,
    pageCache: new WeakMap<object, unknown>(),
    registryCache: new Map(),
    objectCache: new WeakMap(),
    primitiveCache: new Map(),
    unsubs: [],
  };

  const report = (failure: SchemaFailure): void => {
    try {
      (options.onFailure || options.reporter)?.(failure);
    } catch (error) {
      // Reporting should not hide the original schema failure.
      if (mode === 'throw') throw error;
    }

    if (mode === 'report') {
      try {
        options.overlay?.(failure);
      } catch (error) {
        void error;
      }

      if (!options.onFailure && !options.reporter && typeof console !== 'undefined') {
        console.error('[nb_inertia] page schema failure', failure);
      }
    }
  };

  const handleFailure = (failure: SchemaFailure): undefined => {
    report(failure);
    if (mode === 'throw') throw new PageSchemaRuntimeError(failure);
    return undefined;
  };

  const failureFor = (
    value: CachedResult & { ok: false },
    component: string,
    prop: string | undefined,
    phase: SchemaRuntimePhase,
    input: unknown,
  ): SchemaFailure => ({
    ...value.failure,
    kind: value.failure.kind,
    stage: value.failure.kind,
    component,
    prop,
    path: prop ? `${component}.${prop}` : component,
    phase,
    value: input,
  });

  const processValue = (
    component: string,
    prop: string | undefined,
    input: unknown,
    schema: PagePropSchema,
    phase: SchemaRuntimePhase,
  ): { ok: true; value: unknown } | { ok: false; failure: SchemaFailure } => {
    const result = executeSchema(state, schema, input);
    if (result.ok) return result;
    return { ok: false, failure: failureFor(result, component, prop, phase, input) };
  };

  const processProps = (
    component: string,
    props: unknown,
    phase: SchemaRuntimePhase,
    schemaOverride?: PageSchema | PagePropSchema,
  ): unknown => {
    const schema = normalizeSchema(
      schemaOverride || lookupRegistry(options.registry, component, state.registryCache),
    );
    if (!schema || !isRecord(props)) return props;

    const fields = schemaFields(schema);
    const pageRequired = (schema as PageSchema).required;

    const processFields = (
      fieldProps: Record<string, unknown>,
      checkRequired: boolean,
    ): Record<string, unknown> => {
      let next: Record<string, unknown> = fieldProps;

      for (const [prop, propSchemaRaw] of Object.entries(fields || {})) {
        const propSchema = normalizeSchema(propSchemaRaw);
        if (!propSchema) continue;

        if (!hasOwn(fieldProps, prop)) {
          if (
            checkRequired &&
            isCompletePhase(phase) &&
            (isRequiredSchemaField(propSchema, prop) ||
              (Array.isArray(pageRequired) && pageRequired.includes(prop)))
          ) {
            const failure: SchemaFailure = {
              kind: 'validation',
              stage: 'validation',
              component,
              prop,
              path: `${component}.${prop}`,
              phase,
              issues: [{ path: `$.${prop}`, message: 'is required' }],
            };
            handleFailure(failure);
          }
          continue;
        }

        const input = fieldProps[prop];
        const result = processValue(component, prop, input, propSchema, phase);

        if (!result.ok) {
          handleFailure(result.failure);
          if (mode === 'report') {
            if (next === fieldProps) next = { ...fieldProps };
            delete next[prop];
          }
          continue;
        }

        if (!Object.is(result.value, input)) {
          if (next === fieldProps) next = { ...fieldProps };
          next[prop] = result.value;
        }
      }

      return sameOwnValues(fieldProps, next) ? fieldProps : next;
    };

    if (fields) {
      // Generated entries intentionally expose `fields` as the source of
      // truth at the lifecycle boundary. This lets complete snapshots enforce
      // the entry's own `required` list while partial/deferred responses only
      // validate fields present in the wire payload. `fullSchema`/`wireSchema`
      // are retained for explicit whole-page decoders, but must not cause a
      // nested codec to relabel unrelated field validation failures as
      // decode failures here.
      if (isCompletePhase(phase) && typeof schema.validate === 'function') {
        const validation = executeSchema(state, { validate: schema.validate }, props);
        if (!validation.ok) {
          const failure = failureFor(validation, component, undefined, phase, props);
          handleFailure(failure);
          if (mode === 'report') {
            const paths = topLevelIssuePaths(failure.issues);
            if (paths.size === 0) return {};
            const filtered = { ...props };
            for (const key of paths) {
              if (hasOwn(filtered, key)) delete filtered[key];
            }
            return processFields(filtered, false);
          }
        }
      }

      return processFields(props, true);
    }

    // A whole-page parser cannot distinguish a partial payload from a page
    // missing required untouched props. Generated registries expose fields
    // for partial/deferred visits; when they do not, leave the partial wire
    // object untouched rather than inventing validation failures.
    if (!isCompletePhase(phase)) return props;

    const completeSchema =
      normalizeSchema(
        ((schema as PageSchema).fullSchema ??
          (schema as PageSchema).wireSchema ??
          (schema as PageSchema).schema) as PageSchema | PagePropSchema | undefined,
      ) || schema;
    const result = processValue(component, undefined, props, completeSchema, phase);
    if (result.ok) {
      if (!isRecord(result.value)) return result.value;
      // Retain source references for fields that the page parser left alone.
      const parsed = result.value;
      if (sameOwnValues(props, parsed)) return props;
      const shared: Record<string, unknown> = { ...props };
      for (const key of Object.keys(parsed)) {
        shared[key] = Object.is(parsed[key], props[key]) ? props[key] : parsed[key];
      }
      return shared;
    }

    handleFailure(result.failure);
    if (mode !== 'report') return props;

    const paths = topLevelIssuePaths(result.failure.issues);
    if (paths.size === 0) return {};
    const filtered = { ...props };
    for (const key of paths) {
      if (hasOwn(filtered, key)) delete filtered[key];
    }
    return filtered;
  };

  const processModal = (props: Record<string, unknown>): Record<string, unknown> => {
    const modal = props._nb_modal;
    if (!isRecord(modal) || typeof modal.component !== 'string' || !isRecord(modal.props))
      return props;

    const modalSchema = normalizeSchema(
      lookupRegistry(options.registry, modal.component, state.registryCache),
    );
    if (!modalSchema) return props;

    const modalProps = processProps(modal.component, modal.props, 'modal', modalSchema);
    if (Object.is(modalProps, modal.props)) return props;

    return {
      ...props,
      _nb_modal: {
        ...modal,
        props: modalProps,
      },
    };
  };

  const processPage = (page: unknown, phase: SchemaRuntimePhase = state.phase): unknown => {
    if (!enabled || state.disposed || !isObject(page)) return page;
    const pageObject = page as Record<string, unknown>;
    const cached = state.pageCache.get(page);
    if (cached !== undefined) return cached;
    if (typeof pageObject.component !== 'string' || !isRecord(pageObject.props)) return page;

    const component = pageObject.component;
    const schema = normalizeSchema(
      lookupRegistry(options.registry, component, state.registryCache),
    );
    let nextProps = schema
      ? processProps(component, pageObject.props, phase, schema)
      : pageObject.props;
    if (isRecord(nextProps)) nextProps = processModal(nextProps);

    const nextPage = Object.is(nextProps, pageObject.props)
      ? page
      : { ...pageObject, props: nextProps };
    state.pageCache.set(page, nextPage);
    return nextPage;
  };

  const phaseForPage = (_page?: unknown): SchemaRuntimePhase => state.phase;

  const processAndAdopt = (page: unknown, phase: SchemaRuntimePhase): unknown => {
    const processed = processPage(page, phase);
    if (processed !== page && isRecord(page) && isRecord(processed)) {
      try {
        copyPageInto(page as PageLike, processed as PageLike);
        return page;
      } catch (error) {
        // In report mode a frozen page cannot be sanitized in place.  Throwing
        // is safer than allowing the invalid wire payload to reach a page.
        if (mode !== 'throw') {
          const failure: SchemaFailure = {
            kind: 'decode',
            stage: 'decode',
            component: typeof page.component === 'string' ? page.component : '<unknown>',
            phase,
            error,
          };
          report(failure);
          throw new PageSchemaRuntimeError(failure);
        }
        throw error;
      }
    }
    return processed;
  };

  const processPrefetched = (event: unknown): void => {
    if (!isRecord(event) || !isRecord(event.detail)) return;
    const detail = event.detail;
    const response = detail.response;
    if (!isRecord(response)) return;
    const raw = response.data;
    let page: unknown = raw;
    let encoded = false;
    if (typeof raw === 'string') {
      try {
        page = JSON.parse(raw);
        encoded = true;
      } catch {
        return;
      }
    }

    const processed = processPage(page, 'prefetch');
    if (processed === page) return;
    if (encoded) {
      response.data = JSON.stringify(processed);
    } else {
      detail.response = processed;
    }
  };

  const runtime: InstalledSchemaRuntime = {
    enabled,
    mode,
    registry: options.registry,
    router,
    processPage,
    processProps,
    phaseForPage,
    dispose() {
      if (state.disposed) return;
      state.disposed = true;
      for (const unsub of state.unsubs.splice(0)) {
        try {
          unsub();
        } catch (error) {
          void error;
        }
      }
    },
  };

  if (!enabled || !router) return runtime;

  if (typeof router.init === 'function') {
    const originalInit = router.init;
    const wrappedInit = function (this: InertiaRouterLike, params: RouterInitParamsLike) {
      const initialPage = processAndAdopt(params.initialPage, 'initial') as PageLike;
      const originalResolve = params.resolveComponent;
      const resolveComponent = (name: string, page?: PageLike) => {
        const processed = page ? (processAndAdopt(page, phaseForPage(page)) as PageLike) : page;
        return originalResolve(name, processed);
      };
      return originalInit.call(this, { ...params, initialPage, resolveComponent });
    };

    try {
      router.init = wrappedInit;
      const installation = router as InertiaRouterLike & {
        [RUNTIME_INSTALLATION]?: {
          originalInit: typeof originalInit;
          runtime: InstalledSchemaRuntime;
        };
      };
      installation[RUNTIME_INSTALLATION] = { originalInit, runtime };
      state.unsubs.push(() => {
        if (router.init === wrappedInit) router.init = originalInit;
        if (installation[RUNTIME_INSTALLATION]?.runtime === runtime)
          delete installation[RUNTIME_INSTALLATION];
      });
    } catch {
      // Some test doubles expose a read-only init.  Event hooks below still
      // provide best-effort reporting for those adapters.
    }
  }

  if (typeof router.on === 'function' && typeof document !== 'undefined') {
    const subscribe = (event: string, callback: (event: unknown) => unknown): void => {
      try {
        const unsubscribe = router.on?.(event, callback);
        if (typeof unsubscribe === 'function') state.unsubs.push(unsubscribe);
      } catch {
        // SSR and small router test doubles may not support subscriptions.
      }
    };

    subscribe('start', (event) => {
      const visit = isRecord(event) && isRecord(event.detail) ? event.detail.visit : undefined;
      if (isRecord(visit) && visit.deferredProps === true) {
        state.phase = 'deferred';
      } else if (
        isRecord(visit) &&
        ((Array.isArray(visit.only) && visit.only.length > 0) ||
          (Array.isArray(visit.except) && visit.except.length > 0) ||
          (Array.isArray(visit.reset) && visit.reset.length > 0))
      ) {
        state.phase = 'partial';
      } else if (isRecord(visit) && typeof visit.component === 'string') {
        state.phase = 'instant';
      } else {
        state.phase = 'navigation';
      }
    });
    subscribe('beforeUpdate', (event) => {
      const page = isRecord(event) && isRecord(event.detail) ? event.detail.page : undefined;
      if (page) processAndAdopt(page, state.phase);
    });
    subscribe('success', (event) => {
      const page = isRecord(event) && isRecord(event.detail) ? event.detail.page : undefined;
      if (page) processAndAdopt(page, state.phase);
    });
    subscribe('clientVisit', (event) => {
      const page = isRecord(event) && isRecord(event.detail) ? event.detail.page : undefined;
      if (page) processAndAdopt(page, 'instant');
      state.phase = 'instant';
    });
    subscribe('navigate', (event) => {
      const page = isRecord(event) && isRecord(event.detail) ? event.detail.page : undefined;
      if (page) processAndAdopt(page, state.phase);
      state.phase = 'navigation';
    });
    subscribe('prefetched', processPrefetched);
    subscribe('finish', () => {
      if (state.phase !== 'history') state.phase = 'navigation';
    });

    const onPopState = () => {
      state.phase = 'history';
    };
    window.addEventListener('popstate', onPopState);
    state.unsubs.push(() => window.removeEventListener('popstate', onPopState));
  }

  return runtime;
}

/** Create a standalone runtime without patching a router. */
export function createPageSchemaRuntime(options?: PageSchemaRuntimeOptions | false): SchemaRuntime {
  return createRuntime(resolveOptions(options));
}

/**
 * Install the runtime at the Inertia router boundary.  Installation is
 * idempotent for a router instance; a later call returns the existing runtime
 * so framework adapters can safely share the singleton router.
 */
export function installPageSchemaRuntime(
  options?: PageSchemaRuntimeOptions | false,
  router?: InertiaRouterLike,
): InstalledSchemaRuntime {
  const resolved = resolveOptions(options);
  const target = router;

  if (target) {
    const existing = (
      target as InertiaRouterLike & { [RUNTIME_INSTALLATION]?: { runtime: InstalledSchemaRuntime } }
    )[RUNTIME_INSTALLATION];
    if (existing?.runtime) return existing.runtime;
  }

  return createRuntime(resolved, target);
}

export function resolvePageSchemaRuntimeOptions(
  options: PageSchemaAppOptions = {},
): PageSchemaRuntimeOptions | false | undefined {
  if (options.schemaRuntime !== undefined) {
    if (options.schemaRuntime === false) return false;
    return {
      ...options.schemaRuntime,
      registry:
        options.schemaRuntime.registry !== undefined
          ? options.schemaRuntime.registry
          : options.pageSchemas,
    };
  }

  if (options.pageSchemaRuntime !== undefined) {
    if (options.pageSchemaRuntime === false) return false;
    return {
      ...options.pageSchemaRuntime,
      registry:
        options.pageSchemaRuntime.registry !== undefined
          ? options.pageSchemaRuntime.registry
          : options.pageSchemas,
    };
  }

  if (options.pageSchemas !== undefined) return { registry: options.pageSchemas };
  return undefined;
}

/**
 * Framework adapter helper.  It wraps a framework's official
 * `createInertiaApp` while preserving all official options and adding the
 * schema runtime options as a local-only field.
 */
export function createSchemaAwareInertiaApp<TOptions extends PageSchemaAppOptions>(
  createApp: (options: Omit<TOptions, keyof PageSchemaAppOptions>) => unknown,
  options: TOptions,
  router?: InertiaRouterLike,
): unknown {
  const runtimeOptions = resolvePageSchemaRuntimeOptions(options);
  const runtime = installPageSchemaRuntime(
    runtimeOptions === false ? false : runtimeOptions,
    router,
  );
  const {
    schemaRuntime: _schemaRuntime,
    pageSchemaRuntime: _pageSchemaRuntime,
    pageSchemas: _pageSchemas,
    ...coreOptions
  } = options as TOptions & Record<string, unknown>;
  void _schemaRuntime;
  void _pageSchemaRuntime;
  void _pageSchemas;

  if (!runtime.enabled) return createApp(coreOptions as Omit<TOptions, keyof PageSchemaAppOptions>);

  const originalResolve = (coreOptions as { resolve?: unknown }).resolve;
  const wrappedOptions = {
    ...coreOptions,
    ...(typeof originalResolve === 'function'
      ? {
          resolve: (name: string, page?: PageLike) =>
            (originalResolve as (name: string, page?: PageLike) => unknown)(
              name,
              page ? (runtime.processPage(page, runtime.phaseForPage(page)) as PageLike) : page,
            ),
        }
      : {}),
  };

  return createApp(wrappedOptions as Omit<TOptions, keyof PageSchemaAppOptions>);
}
